game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson1')
game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson2')
game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson3')
game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson4')
game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson5')
game.ReplicatedStorage.Events.FinishQuiz:InvokeServer('Lesson6')
